{
 "title": "Air purifier",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "purifier_air_temperature_celsius"
    }
   ]
  },
  {
   "title": "Air humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "purifier_air_humidity_ratio" }
   ]
  },
  {
   "title": "Air quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    { "expr": "purifier_air_quality" }
   ]
  },
  {
   "title": "Light intesity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    { "expr": "purifier_env_illuminance_lux" }
   ]
  },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "purifier_operation_mode != 0", "legendFormat": "{{purifier_operation_mode}}" }
   ]
  },
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purifier_air_temperature_celsius",
     "legendFormat": "{{purifier_air_temperature_celsius}}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "purifier_motor_speed_rpm", "legendFormat": "{{purifier_motor_speed_rpm}}" }
   ]
  },
  {
   "title": "Fan speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    { "expr": "purifier_motor_speed_rpm" }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "purifier_power_state != 0 ", "legendFormat": "{{purifier_power_state}}" }
   ]
  },
  {
   "title": "Air quality",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "purifier_air_quality", "legendFormat": "{{purifier_air_quality}}" }
   ]
  }
 ]
}