name: Docker Image CI

on:
  push:
    branches: 
      - 'master'
  release:
     types: [released]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    
    - name: set master tag
      if: startsWith(${{github.ref}}, "refs/heads/master")
      run: echo "::set-env name=DOCKER_TAG::latest"

    - name: set release tag
      if: startsWith(${{github.ref}}, "refs/tags") 
      env:
        GITHUB_REF: ${{github.ref}}   
      run: echo "::set-env name=DOCKER_TAG::${GITHUB_REF##*/}"

    - name: print docker tag
      run: echo "$DOCKER_TAG"

    #- name: Build the Docker image
      
      #run: docker build . --file src/Dockerfile --tag my-image-name:$(date +%s)
