name: Docker Image CI

on:
  push:
    branches: 
      - 'master'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    
    - name: set master tag
      run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV

    - name: print docker tag
      run: echo "$DOCKER_TAG"

    #- name: Build the Docker image
      
      #run: docker build . --file src/Dockerfile --tag my-image-name:$(date +%s)
