name: Docker Image CI

on:
  release:
     types: [released]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    
    - name: set release tag
      run: echo "DOCKER_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: print docker tag
      run: echo "$DOCKER_TAG"

    #- name: Build the Docker image
      
      #run: docker build . --file src/Dockerfile --tag my-image-name:$(date +%s)
